### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by davidpleydell** [jzaefferer/webpack-jquery-ui#1]
Hi,

Using webpack we get the base theme but we'd like to use one of the other themes.  However only the base theme is downloaded with npm.  
Is there a way we can retrieve themes?
Thanks
David

**Comment by jzaefferer** [comment]
Hello David,

currently there is no official copy of the themes published by jQuery UI. There might be some workaround to install them using npm anyway (you can install from git, and there's a copy of all themes here: https://github.com/jquery/codeorigin.jquery.com/tree/master/cdn/ui/1.12.0-rc.2/themes ).

That said, I've discussed this with a jQuery UI team, and we don't plan to publish other themes on npm. Instead we encourage jQuery UI users to build themes that match their site. At best, our themes would be a boilerplate to get started, but nothing you'd install more than once.

If you have a usecase we missed or want to discuss something related, an issue on https://bugs.jqueryui.com/ would be useful.

Regards
Jörn
