### ISSUE TITLE
Jquery ui

### ISSUE THREAD

**Issue by pablobvch** [jzaefferer/webpack-jquery-ui#5]
Hi everybody,

I'm having several problems to use jquery-ui in my Webpack web.config.js file. This is the file as similar as the example.

--------------------------------------------------

var webpack = require('webpack');
var Clean = require('clean-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    context: __dirname + '/public',
    entry: {
        app: './app/index.js',
        vendor: ['angular','angular-route']
    },
    output: {
        path: __dirname + '/build',
        filename: 'bundle.js'
    },
    module: {
        loaders: [
                {
                  test: /\.css$/,
                  loader: ExtractTextPlugin.extract("style-loader", "css-loader")
                },
                {
                  test: /\.(jpg|png)$/,
                  loader: 'file'
                },
              ]
    },
    resolve : {
      plugins: [
      new webpack.ProvidePlugin({
          "$": "jquery",
          "jQuery": "jquery",
          "window.jQuery": "jquery",
          "window.$": "jquery"
        }),
        new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
        new Clean(['dist']),
		    new ExtractTextPlugin("app.[hash].css"),
		    new HtmlWebpackPlugin({
			     title: 'jQuery UI Autocomplete demo, built with webpack'
		    })
    ]
  }
};
--------------------------------------------------

and this is my index.js file:
--------------------------------------------------
require("jquery");
require('./components/pageA/pageA');
require('./components/pageB/pageB');
require('./assests/js/app');
--------------------------------------------------

I have explored the vendor.bundle.js but I can't see the jquery-ui library.

What can I do???? 

please, help me. I'll thank who can give some clue.

Pablo.

**Comment by jzaefferer** [comment]
Please provide a complete example, otherwise its impossible to help you.
